# Generated by Django 2.0.5 on 2018-10-21 03:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20181020_2239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerinfo',
            old_name='contact_content',
            new_name='consult_content',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
