# Generated by Django 2.0.5 on 2018-10-27 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_auto_20181026_2313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contracttemplate',
            options={'verbose_name_plural': '合同模板'},
        ),
        migrations.AlterModelOptions(
            name='paymentrecord',
            options={'verbose_name_plural': '学员缴费记录表'},
        ),
        migrations.AlterModelOptions(
            name='studentenrollment',
            options={'verbose_name_plural': '学员报名表'},
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='contract_signed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together={('customer', 'class_grade')},
        ),
    ]
