# Generated by Django 2.0.5 on 2018-10-27 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_auto_20181027_1004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerinfo',
            old_name='emergence_contract',
            new_name='emergence_contact',
        ),
    ]
