# Generated by Django 2.0.5 on 2018-10-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_auto_20181028_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='eamil_address',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
