# Generated by Django 2.0.5 on 2018-11-01 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_auto_20181101_1324'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': (('crm_table_obj_list', '可以查看kingadmin每张表里所有的数据'), ('crm_table_list_view', '可以访问kingadmin每张表里每条数据的修改页'), ('crm_table_list_change', '可以对kingadmin每张表的数据进行修改'), ('crm_table_obj_add_view', '可以访问kingadmin数据增加页'), ('crm_table_obj_add', '可以对kingadmin里每张表进行数据添加'), ('crm_table_obj_delete_view', '可以访问kingadmin数据删除页'), ('crm_table_obj_delete', '可以对kingadmin的表里的数据进行删除')), 'verbose_name_plural': '用户表'},
        ),
    ]
